/*
 * Generated by MTK Easy PinMux Tool Version 2.5.4 for 2625. Copyright MediaTek Inc. (C) 2015.
 * 2019-08-13 18:18:14:0753
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char HAL_UART0_RXD_PIN = 2;
const char HAL_UART0_RXD_PIN_M_GPIO = 0;
const char HAL_UART0_RXD_PIN_M_UART0_RXD = 1;
const char HAL_UART0_RXD_PIN_M_EINT = 7;
const char HAL_UART0_RXD_PIN_M_DEBUGMON2 = 8;


const char HAL_UART2_RXD_PIN = 3;
const char HAL_UART2_RXD_PIN_M_GPIO = 0;
const char HAL_UART2_RXD_PIN_M_UART2_RXD = 1;
const char HAL_UART2_RXD_PIN_M_I2C1_SCL = 2;
const char HAL_UART2_RXD_PIN_M_I2S0_CK = 3;
const char HAL_UART2_RXD_PIN_M_KP_ROW0 = 4;
const char HAL_UART2_RXD_PIN_M_UART1_RXD = 5;
const char HAL_UART2_RXD_PIN_M_CLKO = 6;
const char HAL_UART2_RXD_PIN_M_EINT = 7;
const char HAL_UART2_RXD_PIN_M_DEBUGMON3 = 8;


const char HAL_UART2_TXD_PIN = 4;
const char HAL_UART2_TXD_PIN_M_GPIO = 0;
const char HAL_UART2_TXD_PIN_M_UART2_TXD = 1;
const char HAL_UART2_TXD_PIN_M_I2C1_SDA = 2;
const char HAL_UART2_TXD_PIN_M_I2S0_MCLK = 3;
const char HAL_UART2_TXD_PIN_M_KP_ROW1 = 4;
const char HAL_UART2_TXD_PIN_M_UART1_TXD = 5;
const char HAL_UART2_TXD_PIN_M_PWM0 = 6;
const char HAL_UART2_TXD_PIN_M_EINT = 7;
const char HAL_UART2_TXD_PIN_M_DEBUGMON4 = 8;


const char HAL_UART0_TXD_PIN = 5;
const char HAL_UART0_TXD_PIN_M_GPIO = 0;
const char HAL_UART0_TXD_PIN_M_UART0_TXD = 1;
const char HAL_UART0_TXD_PIN_M_EINT = 7;
const char HAL_UART0_TXD_PIN_M_DEBUGMON5 = 8;


const char HAL_I2C_MASTER_0_SCL_PIN = 6;
const char HAL_I2C_MASTER_0_SCL_PIN_M_GPIO = 0;
const char HAL_I2C_MASTER_0_SCL_PIN_M_SDIO_SLV0_DAT1 = 1;
const char HAL_I2C_MASTER_0_SCL_PIN_M_SPI_MST0_SIO3 = 2;
const char HAL_I2C_MASTER_0_SCL_PIN_M_I2S0_WS = 3;
const char HAL_I2C_MASTER_0_SCL_PIN_M_I2C0_SCL = 4;
const char HAL_I2C_MASTER_0_SCL_PIN_M_NBIOT_PRI = 5;
const char HAL_I2C_MASTER_0_SCL_PIN_M_GPS_BLANKING = 6;
const char HAL_I2C_MASTER_0_SCL_PIN_M_EINT = 7;
const char HAL_I2C_MASTER_0_SCL_PIN_M_DEBUGMON6 = 8;


const char HAL_I2C_MASTER_0_SDA_PIN = 7;
const char HAL_I2C_MASTER_0_SDA_PIN_M_GPIO = 0;
const char HAL_I2C_MASTER_0_SDA_PIN_M_SDIO_SLV0_CMD = 1;
const char HAL_I2C_MASTER_0_SDA_PIN_M_SPI_MST0_SIO2 = 2;
const char HAL_I2C_MASTER_0_SDA_PIN_M_I2S0_TX = 3;
const char HAL_I2C_MASTER_0_SDA_PIN_M_I2C0_SDA = 4;
const char HAL_I2C_MASTER_0_SDA_PIN_M_PWM1 = 5;
const char HAL_I2C_MASTER_0_SDA_PIN_M_GPS_FRAME_SYNC = 6;
const char HAL_I2C_MASTER_0_SDA_PIN_M_EINT = 7;
const char HAL_I2C_MASTER_0_SDA_PIN_M_DEBUGMON7 = 8;


const char HAL_SPI_MASTER0_CS_PIN = 8;
const char HAL_SPI_MASTER0_CS_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER0_CS_PIN_M_SDIO_SLV0_DAT0 = 1;
const char HAL_SPI_MASTER0_CS_PIN_M_SPI_MST0_CS = 2;
const char HAL_SPI_MASTER0_CS_PIN_M_I2S0_CK = 3;
const char HAL_SPI_MASTER0_CS_PIN_M_PWM1 = 4;
const char HAL_SPI_MASTER0_CS_PIN_M_NBIOT_ACT = 5;
const char HAL_SPI_MASTER0_CS_PIN_M_PAD_DFUNC_SFCK = 6;
const char HAL_SPI_MASTER0_CS_PIN_M_EINT = 7;
const char HAL_SPI_MASTER0_CS_PIN_M_DEBUGMON8 = 8;


const char HAL_SPI_MASTER0_MISO_PIN = 9;
const char HAL_SPI_MASTER0_MISO_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER0_MISO_PIN_M_SDIO_SLV0_CLK = 1;
const char HAL_SPI_MASTER0_MISO_PIN_M_SPI_MST0_MISO = 2;
const char HAL_SPI_MASTER0_MISO_PIN_M_I2S0_MCLK = 3;
const char HAL_SPI_MASTER0_MISO_PIN_M_RF_CONFL_DET_IRQ_B = 4;
const char HAL_SPI_MASTER0_MISO_PIN_M_WLAN_ACT = 5;
const char HAL_SPI_MASTER0_MISO_PIN_M_PAD_DFUNC_SFCS0 = 6;
const char HAL_SPI_MASTER0_MISO_PIN_M_EINT = 7;
const char HAL_SPI_MASTER0_MISO_PIN_M_DEBUGMON9 = 8;


const char HAL_SPI_MASTER0_MOSI_PIN = 10;
const char HAL_SPI_MASTER0_MOSI_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER0_MOSI_PIN_M_SDIO_SLV0_DAT3 = 1;
const char HAL_SPI_MASTER0_MOSI_PIN_M_SPI_MST0_MOSI = 2;
const char HAL_SPI_MASTER0_MOSI_PIN_M_I2C1_SCL = 3;
const char HAL_SPI_MASTER0_MOSI_PIN_M_GPS_FRAME_SYNC = 4;
const char HAL_SPI_MASTER0_MOSI_PIN_M_PMU_RGU_RSTB = 5;
const char HAL_SPI_MASTER0_MOSI_PIN_M_CLKO = 6;
const char HAL_SPI_MASTER0_MOSI_PIN_M_EINT = 7;
const char HAL_SPI_MASTER0_MOSI_PIN_M_DEBUGMON10 = 8;


const char HAL_SPI_MASTER0_SCK_PIN = 11;
const char HAL_SPI_MASTER0_SCK_PIN_M_GPIO = 0;
const char HAL_SPI_MASTER0_SCK_PIN_M_SDIO_SLV0_DAT2 = 1;
const char HAL_SPI_MASTER0_SCK_PIN_M_SPI_MST0_SCK = 2;
const char HAL_SPI_MASTER0_SCK_PIN_M_GPS_BLANKING = 4;
const char HAL_SPI_MASTER0_SCK_PIN_M_PMU_GOTO_SLEEP = 5;
const char HAL_SPI_MASTER0_SCK_PIN_M_PWMSG0 = 6;
const char HAL_SPI_MASTER0_SCK_PIN_M_EINT = 7;
const char HAL_SPI_MASTER0_SCK_PIN_M_DEBUGMON11 = 8;


const char HAL_UART1_RXD_PIN = 16;
const char HAL_UART1_RXD_PIN_M_GPIO = 0;
const char HAL_UART1_RXD_PIN_M_MSDC0_DAT2 = 1;
const char HAL_UART1_RXD_PIN_M_SPI_SLV0_SIO2 = 2;
const char HAL_UART1_RXD_PIN_M_I2C1_SCL = 3;
const char HAL_UART1_RXD_PIN_M_UART1_RXD = 4;
const char HAL_UART1_RXD_PIN_M_GPS_FRAME_SYNC = 5;
const char HAL_UART1_RXD_PIN_M_PWMSG0 = 6;
const char HAL_UART1_RXD_PIN_M_EINT = 7;
const char HAL_UART1_RXD_PIN_M_DEBUGMON4 = 8;


const char HAL_UART1_TXD_PIN = 17;
const char HAL_UART1_TXD_PIN_M_GPIO = 0;
const char HAL_UART1_TXD_PIN_M_MSDC0_DAT3 = 1;
const char HAL_UART1_TXD_PIN_M_SPI_SLV0_SIO3 = 2;
const char HAL_UART1_TXD_PIN_M_I2C1_SDA = 3;
const char HAL_UART1_TXD_PIN_M_UART1_TXD = 4;
const char HAL_UART1_TXD_PIN_M_XO_WAKEUP = 5;
const char HAL_UART1_TXD_PIN_M_EINT = 7;
const char HAL_UART1_TXD_PIN_M_DEBUGMON5 = 8;


const char HAL_UART1_CTS_PIN = 18;
const char HAL_UART1_CTS_PIN_M_GPIO = 0;
const char HAL_UART1_CTS_PIN_M_MSDC1_DAT2 = 1;
const char HAL_UART1_CTS_PIN_M_SPI_MST1_SIO2 = 2;
const char HAL_UART1_CTS_PIN_M_UART2_RXD = 3;
const char HAL_UART1_CTS_PIN_M_UART1_CTS = 4;
const char HAL_UART1_CTS_PIN_M_GPS_BLANKING = 5;
const char HAL_UART1_CTS_PIN_M_RF_CONFL_DET_IRQ_B = 6;
const char HAL_UART1_CTS_PIN_M_EINT = 7;
const char HAL_UART1_CTS_PIN_M_DEBUGMON10 = 8;


const char HAL_UART1_RTS_PIN = 23;
const char HAL_UART1_RTS_PIN_M_GPIO = 0;
const char HAL_UART1_RTS_PIN_M_MSDC1_DAT3 = 1;
const char HAL_UART1_RTS_PIN_M_SPI_MST1_SIO3 = 2;
const char HAL_UART1_RTS_PIN_M_I2C1_SDA = 3;
const char HAL_UART1_RTS_PIN_M_UART2_TXD = 4;
const char HAL_UART1_RTS_PIN_M_UART1_RTS = 5;
const char HAL_UART1_RTS_PIN_M_EINT = 7;
const char HAL_UART1_RTS_PIN_M_DEBUGMON3 = 8;


const char HAL_AUXADC_0_PIN = 30;
const char HAL_AUXADC_0_PIN_M_GPIO = 0;
const char HAL_AUXADC_0_PIN_M_I2S1_RX = 1;
const char HAL_AUXADC_0_PIN_M_AP_JTDI = 2;
const char HAL_AUXADC_0_PIN_M_CLKO = 3;
const char HAL_AUXADC_0_PIN_M_MD_JTMS = 4;
const char HAL_AUXADC_0_PIN_M_AUXADC0 = 5;
const char HAL_AUXADC_0_PIN_M_EINT = 7;
const char HAL_AUXADC_0_PIN_M_DEBUGMON2 = 8;


const char HAL_AUXADC_1_PIN = 31;
const char HAL_AUXADC_1_PIN_M_GPIO = 0;
const char HAL_AUXADC_1_PIN_M_I2S1_TX = 1;
const char HAL_AUXADC_1_PIN_M_AP_JRSTB = 2;
const char HAL_AUXADC_1_PIN_M_UART2_RXD = 3;
const char HAL_AUXADC_1_PIN_M_MD_JTCK = 4;
const char HAL_AUXADC_1_PIN_M_AUXADC1 = 5;
const char HAL_AUXADC_1_PIN_M_EINT = 7;
const char HAL_AUXADC_1_PIN_M_DEBUGMON3 = 8;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_UART0_DTE_DCD_PIN = 0xff;
const char HAL_UART0_DTE_DSR_PIN = 0xff;
const char HAL_UART0_DTE_DTR_PIN = 0xff;
const char HAL_UART0_DTE_RI_PIN = 0xff;
const char HAL_UART1_DTE_DCD_PIN = 0xff;
const char HAL_UART1_DTE_DSR_PIN = 0xff;
const char HAL_UART1_DTE_DTR_PIN = 0xff;
const char HAL_UART1_DTE_RI_PIN = 0xff;
const char HAL_UART2_DTE_DCD_PIN = 0xff;
const char HAL_UART2_DTE_DSR_PIN = 0xff;
const char HAL_UART2_DTE_DTR_PIN = 0xff;
const char HAL_UART2_DTE_RI_PIN = 0xff;
const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_GNSS_32K_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char EXT_NTC_POWER_SW_PIN = 0xff;
const char EXT_NTC_ADC_PIN = 0xff;
const char EXT_DSP_POWER_SW_PIN = 0xff;
const char EXT_DSP_CLK_SW_PIN = 0xff;
const char EXT_DSP_RTC_CLK_SW_PIN = 0xff;
const char EXT_DSP_32K_CLK_PIN = 0xff;
const char NOTIFY_EXT_DSP_IRQ_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;
const char CHARGER_POWER_GOOD_PIN = 0xff;
const char CHARGER_CHARGING_STATE_PIN = 0xff;
const char BSP_CCCI_UART_RXD_PIN = 0xff;
const char BSP_CCCI_UART_TXD_PIN = 0xff;
const char BSP_WAKEUP_OUT = 0xff;
const char ANT_SPDT_POWER_CTRL_PIN = 0xff;


const char HAL_I2C_MASTER_1_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_1_SDA_PIN = 0xff;
const char HAL_I2C_MASTER_2_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_2_SDA_PIN = 0xff;
const char HAL_AUXADC_2_PIN = 0xff;
const char HAL_AUXADC_3_PIN = 0xff;
const char HAL_AUXADC_4_PIN = 0xff;
const char HAL_SDIO_SLV_CK_PIN = 0xff;
const char HAL_SDIO_SLV_CM_PIN = 0xff;
const char HAL_SDIO_SLV_DA0_PIN = 0xff;
const char HAL_SDIO_SLV_DA1_PIN = 0xff;
const char HAL_SDIO_SLV_DA2_PIN = 0xff;
const char HAL_SDIO_SLV_DA3_PIN = 0xff;
const char HAL_MSDC_0_CK_PIN = 0xff;
const char HAL_MSDC_0_CM_PIN = 0xff;
const char HAL_MSDC_0_DA0_PIN = 0xff;
const char HAL_MSDC_0_DA1_PIN = 0xff;
const char HAL_MSDC_0_DA2_PIN = 0xff;
const char HAL_MSDC_0_DA3_PIN = 0xff;
const char HAL_MSDC_1_CK_PIN = 0xff;
const char HAL_MSDC_1_CM_PIN = 0xff;
const char HAL_MSDC_1_DA0_PIN = 0xff;
const char HAL_MSDC_1_DA1_PIN = 0xff;
const char HAL_MSDC_1_DA2_PIN = 0xff;
const char HAL_MSDC_1_DA3_PIN = 0xff;
const char HAL_PWM_0_PIN = 0xff;
const char HAL_PWM_1_PIN = 0xff;
const char HAL_PWM_2_PIN = 0xff;
const char HAL_PWM_3_PIN = 0xff;
const char HAL_PWMSG_0_PIN = 0xff;
const char HAL_PWMSG_1_PIN = 0xff;
const char HAL_UART2_RTS_PIN = 0xff;
const char HAL_UART2_CTS_PIN = 0xff;
const char HAL_UART3_RXD_PIN = 0xff;
const char HAL_UART3_TXD_PIN = 0xff;
const char HAL_SPI_MASTER0_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER0_SIO3_PIN = 0xff;
const char HAL_SPI_MASTER1_CS_PIN = 0xff;
const char HAL_SPI_MASTER1_SCK_PIN = 0xff;
const char HAL_SPI_MASTER1_MISO_PIN = 0xff;
const char HAL_SPI_MASTER1_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER1_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER1_SIO3_PIN = 0xff;
const char HAL_SPI_SLV0_CS_PIN = 0xff;
const char HAL_SPI_SLV0_SCK_PIN = 0xff;
const char HAL_SPI_SLV0_MISO_PIN = 0xff;
const char HAL_SPI_SLV0_MOSI_PIN = 0xff;
const char HAL_SPI_SLV0_SIO2_PIN = 0xff;
const char HAL_SPI_SLV0_SIO3_PIN = 0xff;
const char HAL_I2S0_RX_PIN = 0xff;
const char HAL_I2S0_TX_PIN = 0xff;
const char HAL_I2S0_WS_PIN = 0xff;
const char HAL_I2S0_BCLK_PIN = 0xff;
const char HAL_I2S0_MCLK_PIN = 0xff;
const char HAL_I2S1_RX_PIN = 0xff;
const char HAL_I2S1_TX_PIN = 0xff;
const char HAL_I2S1_WS_PIN = 0xff;
const char HAL_I2S1_BCLK_PIN = 0xff;
const char HAL_I2S1_MCLK_PIN = 0xff;
const char HAL_KEYPAD_COL0_PIN = 0xff;
const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_COL2_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char HAL_KEYPAD_ROW1_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;





