/*
 * Generated by MTK Easy PinMux Tool Version 2.5.4 for 2625. Copyright MediaTek Inc. (C) 2015.
 * 2019-04-24 18:43:52:0409
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;
const unsigned char HAL_UART0_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART1_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART2_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DSR_EINT = 0xff;
const unsigned char EXT_DSP_TRIGGER_EINT = 0xff;
const unsigned char BSP_EINTKEY0_EINT = 0xff;
const unsigned char BSP_EINTKEY1_EINT = 0xff;
const unsigned char BSP_EINTKEY2_EINT = 0xff;
const unsigned char CHARGER_POWER_GOOD_EINT = 0xff;
const unsigned char CHARGER_CHARGING_STATE_EINT = 0xff;



