import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Glob("*.c")

group = DefineGroup('samples', src, depend = ['RT_USING_NB_SAMPLES'], CPPPATH = CPPPATH)

Return('group')
